name: firestore_odm
description: Type-safe Firestore ODM with code generation support. Generate type-safe Firestore operations with annotations.
version: 1.1.1
homepage: https://github.com/sylphxltd/firestore_odm
repository: https://github.com/sylphxltd/firestore_odm
issue_tracker: https://github.com/sylphxltd/firestore_odm/issues
documentation: https://pub.dev/documentation/firestore_odm/latest/

topics:
  - firestore
  - odm
  - database
  - flutter
  - code-generation

environment:
  sdk: '^3.8.1'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  cloud_firestore_platform_interface: ^6.5.0
  meta: ^1.9.1
  firestore_odm_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  very_good_analysis: ^6.0.0

# Publishing to pub.dev (default when omitted)