name: firestore_odm
description: Type-safe Firestore ODM with code generation support
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  meta: ^1.9.1
  firestore_odm_annotation:
    path: ../firestore_odm_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0