name: firestore_odm_workspace
repository: https://github.com/sylphxltd/firestore_odm

packages:
  - packages/firestore_odm_annotation
  - packages/firestore_odm
  - packages/firestore_odm_builder
  - flutter_example

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    # Only allow versioning for actual publishable packages
    includeScopes: false
    updateGitTagRefs: true
    workspaceChangelog: true

scripts:
  # Development scripts
  analyze:
    run: dart analyze .
    description: Run static analysis on all packages.
    packageFilters:
      ignore:
        - flutter_example

  test:
    run: dart test
    description: Run tests in all packages.
    packageFilters:
      ignore:
        - flutter_example

  format:
    run: dart format .
    description: Format all Dart files.

  format:check:
    run: dart format --output=none --set-exit-if-changed .
    description: Check if all files are formatted correctly.

  build:example:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Generate code for the example.
    packageFilters:
      scope: flutter_example

  # Testing scripts
  test:unit:
    run: dart test
    description: Run unit tests.
    packageFilters:
      ignore:
        - flutter_example

  test:integration:
    run: flutter test
    description: Run integration tests.
    packageFilters:
      scope: flutter_example

  test:all:
    run: |
      melos run test:unit --no-select &&
      melos run test:integration --no-select
    description: Run all tests (unit + integration).

  # Code quality scripts
  analyze:fix:
    run: dart fix --apply
    description: Apply automated fixes.
    packageFilters:
      ignore:
        - flutter_example

  check:
    run: |
      melos run format:check --no-select &&
      melos run analyze --no-select &&
      melos run test:all --no-select
    description: Run all checks (format, analyze, test).

  # Release preparation scripts
  clean:
    run: |
      flutter clean &&
      dart pub cache repair
    description: Clean build artifacts and repair pub cache.
    packageFilters:
      flutter: true

  deps:
    run: dart pub deps
    description: Show dependency tree.

  deps:outdated:
    run: dart pub outdated
    description: Check for outdated dependencies.

  # Publishing scripts
  version:check:
    run: melos version --dry-run
    description: Preview version changes without applying them.

  publish:dry-run:
    run: dart pub publish --dry-run
    description: Validate packages before publishing.
    exec:
      concurrency: 1
    packageFilters:
      noPrivate: true

  publish:
    run: dart pub publish --force
    description: Publish packages to pub.dev.
    exec:
      concurrency: 1
    packageFilters:
      noPrivate: true