name: firestore_odm_workspace
repository: https://github.com/sylphxltd/firestore_odm

packages:
  - apps/**
  - packages/**

command:
  version:
    updateGitTagRefs: true
    workspaceChangelog: true

scripts:
  generate:
    run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
    
  # Development scripts
  analyze:
    run: dart analyze .
    description: Run static analysis on all packages.
    packageFilters:
      ignore:
        - flutter_example

  test:
    run: dart test
    description: Run tests in all packages.
    packageFilters:
      ignore:
        - flutter_example

  fix:
    run: dart fix --apply
    description: Apply automated fixes to all packages.

  format:check:
    run: dart format --output=none --set-exit-if-changed .
    description: Check if all files are formatted correctly.

  build:example:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Generate code for the example.
    packageFilters:
      scope: flutter_example

  # Testing scripts
  test:unit:
    run: dart test
    description: Run unit tests.
    packageFilters:
      ignore:
        - flutter_example

  test:integration:
    run: flutter test
    description: Run integration tests.
    packageFilters:
      scope: flutter_example

  test:all:
    run: |
      melos run test:unit --no-select &&
      melos run test:integration --no-select
    description: Run all tests (unit + integration).

  # Code quality scripts
  analyze:fix:
    run: dart fix --apply
    description: Apply automated fixes.
    packageFilters:
      ignore:
        - flutter_example

  check:
    run: |
      melos run format:check --no-select &&
      melos run analyze --no-select &&
      melos run test:all --no-select
    description: Run all checks (format, analyze, test).

  # Release preparation scripts
  clean:
    run: |
      flutter clean &&
      dart pub cache repair
    description: Clean build artifacts and repair pub cache.
    packageFilters:
      flutter: true

  deps:
    run: dart pub deps
    description: Show dependency tree.

  deps:outdated:
    run: dart pub outdated
    description: Check for outdated dependencies.

  sync:readme:
    run: |
      copy README.md packages\firestore_odm\README.md
      copy README.md packages\firestore_odm_annotation\README.md
      copy README.md packages\firestore_odm_builder\README.md
    description: Sync README.md to all packages.

