name: firestore_odm_workspace
repository: https://github.com/your-org/firestore_odm

packages:
  - packages/firestore_odm_annotation
  - packages/firestore_odm
  - packages/firestore_odm_builder
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze .
    description: Run static analysis on all packages.

  test:
    run: dart test
    description: Run tests in all packages.

  format:
    run: dart format .
    description: Format all Dart files.

  build:example:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Generate code for the example.
    packageFilters:
      scope: example