name: firestore_odm_workspace
description: A monorepo workspace for Firestore ODM packages
version: 1.0.0
homepage: https://github.com/sunrimii/firestore_odm
repository: https://github.com/sunrimii/firestore_odm

publish_to: none

environment:
  sdk: '^3.9.2'

dev_dependencies:
  melos: ^7.1.1
  very_good_analysis: ^10.0.0

workspace:
  - packages/firestore_odm
  - packages/firestore_odm_annotation
  - packages/firestore_odm_builder
