name: firestore_odm
description: A powerful Firestore ODM (Object Document Mapper) for Flutter with code generation support
version: 1.0.0
homepage: https://github.com/your-org/firestore_odm

environment:
  sdk: '^3.8.1'

workspace:
  - packages/firestore_odm_annotation
  - packages/firestore_odm_builder

dev_dependencies:
  melos: ^6.0.0