name: firestore_odm_builder
description: Code generator for Firestore ODM annotations. Generates type-safe Firestore operations from annotated classes.
version: 2.0.1
homepage: https://github.com/sylphxltd/firestore_odm
repository: https://github.com/sylphxltd/firestore_odm
issue_tracker: https://github.com/sylphxltd/firestore_odm/issues
documentation: https://pub.dev/documentation/firestore_odm_builder/latest/

topics:
  - firestore
  - odm
  - code-generation
  - build-runner
  - flutter

environment:
  sdk: '^3.8.1'

dependencies:
  build: ^2.4.1
  source_gen: ^2.0.0
  analyzer: ^7.4.5
  firestore_odm_annotation:
  fast_immutable_collections: ^11.0.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  very_good_analysis: ^6.0.0

# Publishing to pub.dev (default when omitted)