name: firestore_odm_builder
description: Code generator for Firestore ODM annotations
version: 1.0.0
homepage: https://github.com/your-org/firestore_odm

environment:
  sdk: '^3.8.1'

resolution: workspace

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1

dev_dependencies:
  build_runner: ^2.4.9
  very_good_analysis: ^6.0.0