name: firestore_odm_annotation
description: Pure annotations for Firestore ODM code generation
version: 1.0.0

environment:
  sdk: '^3.8.1'
  
dependencies:
  meta: ^1.9.1

dev_dependencies:
  very_good_analysis: ^6.0.0