name: firestore_odm_annotation
description: Pure annotations for Firestore ODM code generation. Provides the core annotations used to generate type-safe Firestore ODM code.
version: 4.0.0-dev.1
homepage: https://github.com/sunrimii/firestore_odm
repository: https://github.com/sunrimii/firestore_odm
issue_tracker: https://github.com/sunrimii/firestore_odm/issues
documentation: https://sylphxltd.github.io/firestore_odm/
resolution: workspace

topics:
  - firestore
  - odm
  - annotations
  - code-generation
  - flutter

environment:
  sdk: '^3.9.2'
  
dependencies:
  meta: ^1.16.0

dev_dependencies:
  very_good_analysis: ^10.0.0
